### ISSUE TITLE
Clock is partially off-screen on a 4K Monitor

### ISSUE THREAD

**Issue by cnapolit** [Mike-Aniki/Aniki-Lite#1]
On a 3840x2160 display, the clock in the top-right corner is not fully in view.
![image](https://github.com/user-attachments/assets/76f3b7ab-870d-4e8b-8793-31f0c8d6d5d8)

P.S. love the theme! Always nice to new takes :)

**Comment by Mike-Aniki** [comment]
I have released version 1.0.2 which solves this problem.

**Comment by Mike-Aniki** [comment]
Problem completely solved in version 1.1
