### ISSUE TITLE
Freezing/Crashing while selecting options

### ISSUE THREAD

**Issue by cnapolit** [Mike-Aniki/Aniki-Lite#2]
Wasn't clear to me what causes this, as I recreated it through different means a few times.
Here's a recording of one of the instances (I have a higher resolution version if needed, it was too big for github):
https://github.com/user-attachments/assets/6f19da76-3dda-48cd-8756-e8103985c2ae

**Comment by cnapolit** [comment]
Nothing too helpful in the logs:
```
28-08 08:17:29.331|INFO |PlayniteApplication:Application 10.34.0.23368 started
28-08 08:17:42.565|DEBUG|BaseCollectionView:Refreshing collection view filter.
28-08 08:17:46.581|WARN |MainViewModelBase:Lost keyboard focus from known controls, trying to focus something.
28-08 08:17:46.581|DEBUG|MainViewModelBase:Focusing Playnite.FullscreenApp.Controls.ButtonEx: 
```

**Comment by Mike-Aniki** [comment]
Thanks for your bug feedback, it helps to improve the theme. 
I was not able to reproduce the problem, but I think it is related to the fact of displaying the filter menu while the source view is displayed in addition to being inestetic it must cause the crash for some people, so I made unusable the filter menu button when you are on the source view in the update 1.0.2 released just now.

**Comment by Mike-Aniki** [comment]
Does the problem persist with updates ?
